### ISSUE TITLE
test script

### ISSUE THREAD

**Issue by SherlockHua1995** [IDT-ITI/MMFusion-IML#1]
hi,it's a wonderful project.
I want to test the model for personal Image.
Is there any test script for inference on personal image？
thank you.

**Comment by kostino** [comment]
Thank you for your interest in our work! I have added the inference.py script so you can quickly run our model on a personal image.
You need to place your image in the /data directory and then use the inference.py script. For example, if I have an image named example.png I move it to data/example.png and change the argument on https://github.com/IDT-ITI/MMFusion-IML/blob/4e7ab9b68e7533bed669b2af90fcab144e7e7dee/inference.py#L17 to "example.png" and run inference.py.

**Comment by SherlockHua1995** [comment]
Thank you for your timely reply.
best wishes!

**Comment by SherlockHua1995** [comment]
hi, models/backbones/ miss one file？`from.cmnext import CMNeXt`  failed.

**Comment by SherlockHua1995** [comment]
@kostino Hi.In inference.py, target is not saved.
_mask.png is not generated.

**Comment by SherlockHua1995** [comment]
> @kostino Hi.In inference.py, target is not saved. _mask.png is not generated.

I have solved this.

**Comment by kostino** [comment]
Thanks for the feedback, fixed those bugs in 608acc73bf6a7209f64a023c5d65c91f0e724091
