### ISSUE TITLE
What is the threshold would be the best for detection = torch.sigmoid(detection)?

### ISSUE THREAD

**Issue by licho123** [IDT-ITI/MMFusion-IML#11]

**Comment by kostino** [comment]
Hi, I don't really get what you're asking. If you want to know what threshold to set for getting the prediction from the detection score, I suggest 0.5 . For some datasets, you can get better detection metrics if you change the threshold per dataset, but I don't recommend it as it limits your model's usability for real data, as you don't know where to set the threshold.
