### ISSUE TITLE
Only two pretrained weights are used in training and inference script even though in paper it is mentioned 3 filters are used

### ISSUE THREAD

**Issue by man0007** [IDT-ITI/MMFusion-IML#12]
HI,

I could see in the ex_example_phase2.yml file that you are loading only two pretrained filters but in the paper you have mentioned that you are using all three filters for prediction: 

  PRETRAINED: 'pretrained/segformer/mit_b2.pth'
  NP_WEIGHTS: 'pretrained/noiseprint/np++.pth'

**Comment by kostino** [comment]
Hi, 
the PRETRAINED checkpoint in the yaml file is the checkpoint for the segformer as we mention in the paper. We are using three filters that we select through the MODALS flag in the yaml file. See here: https://github.com/IDT-ITI/MMFusion-IML/blob/33c1730d35d8a7dd9b80d42d48e982c6748dfcbd/experiments/ec_example_phase2.yaml#L43
You can find the implementation of all filters in the models/modal_extract.py file: https://github.com/IDT-ITI/MMFusion-IML/blob/main/models/modal_extract.py#L13-L63
