### ISSUE TITLE
Is the 'pretrained/segformer/mit_b2.pth' and SRM filter mentioned in the paper the same?

### ISSUE THREAD

**Issue by man0007** [IDT-ITI/MMFusion-IML#13]
Hi,

I could see that you have not specifically mentioned anything in the code about the SRM filter that is mentioned in the paper.

Is the 'pretrained/segformer/mit_b2.pth' and SRM filter mentioned in the paper are the same?

**Comment by kostino** [comment]
Hi,
The  'pretrained/segformer/mit_b2.pth' checkpoint is the checkpoint of the segformer backbone pretrained on imagenet, as mentioned in the paper. The implementation of the SRM filter is here:
https://github.com/IDT-ITI/MMFusion-IML/blob/33c1730d35d8a7dd9b80d42d48e982c6748dfcbd/common/utils.py#L58-L87
