### ISSUE TITLE
Could you please share how did you train the noise print ++?

### ISSUE THREAD

**Issue by licho123** [IDT-ITI/MMFusion-IML#16]
"We replicated the training of TruFor for the purposes
of our ablation study and we discovered a large variance in Localization results
between training runs. For this purpose, we train our networks 4 times and report average localization performance in terms of average pixel F1 in Table 4."

**Comment by kostino** [comment]
Hi, for NP++ we got the pretrained checkpoint from the TruFor github repo: 
https://github.com/grip-unina/TruFor
