### ISSUE TITLE
About the weight of BayerConv2D

### ISSUE THREAD

**Issue by Kelfvin** [IDT-ITI/MMFusion-IML#3]
Your research results are excellent! However, I have a question that I hope you can answer.

How are the weights for BayerConv2D configured? There are learnable parameters inside this module, so why aren't they loaded from the weight file during initialization?

**Comment by kostino** [comment]
Hello, thank you for your interest in our paper and code!
For the phase 1 training, the weights are loaded in this way:
https://github.com/IDT-ITI/MMFusion-IML/blob/608acc73bf6a7209f64a023c5d65c91f0e724091/ec_train.py#L53-L59
You need to download the pretrained weights as described in pretrained/README.md

For phase 2 the weights are loaded from the checkpoint of the modal extractor module (this is where they are saved after phase 1 training):
https://github.com/IDT-ITI/MMFusion-IML/blob/608acc73bf6a7209f64a023c5d65c91f0e724091/ec_train_phase2.py#L60
