### ISSUE TITLE
How are the weights of BayerConv2D pre-trained?

### ISSUE THREAD

**Issue by fuqianya** [IDT-ITI/MMFusion-IML#4]
Hi,

First off, I want to express my appreciation for your impressive work. I've been going through the code, and I noticed that in training phase 1, the weights for BayerConv2D are loaded from `pretrained/modal_extractor/bayar_mhsa.pth`. Could you please provide some details on how the weights in `bayar_mhsa.pth` are pre-trained? I'm interested in understanding the pre-training process used for these weights.

Thank you!

**Comment by kostino** [comment]
Hello, and thank you for your interest in our work! The BayarConv2D layer is pretrained as a sole auxiliary branch as described in Section 3.2->paragraph "Bayar Convolution" of our paper (https://arxiv.org/pdf/2312.01790.pdf). This is the checkpoint that is used for the initialization afterward.
