### ISSUE TITLE
About test_detection.py

### ISSUE THREAD

**Issue by HuCutie** [IDT-ITI/MMFusion-IML#6]
I downloaded the pretrained models via the link below /ckpt/README.md, but when I run test_detection.py, it asserted "RuntimeError: Error(s) in loading state_dict for CMNeXtWithConf:"
![QQ截图20240402201345](https://github.com/IDT-ITI/MMFusion-IML/assets/40013434/9e46cad0-829c-4758-a33b-ea89eaf7008a)

I believe it may because you update your network but models, could you please reply?

**Comment by licho123** [comment]
@HuCutie  you need to make some code changes for using Late Fusion pre-trained model
1) Change backbone in the exp yaml file:
    BACKBONE: WSCMNeXtMHSA-B2
2) Use WSCMNeXtWithConf to create model instance  
#model = CMNeXtWithConf(config.MODEL)
model = WSCMNeXtWithConf(config.MODEL)

**Comment by kostino** [comment]
Thanks @licho123 for the reply
