### ISSUE TITLE
Clarification on Different MHSA Variants in CMNeXt Model

### ISSUE THREAD

**Issue by fuqianya** [IDT-ITI/MMFusion-IML#7]
Hi,

Could someone explain the differences between cmnext_mhsa, mixcmnext_mhsa, and ws_cmnext_mhsa? I am trying to understand how these variants compare and their specific use cases or benefits.

Thank you for your assistance!

**Comment by kostino** [comment]
Hi, you can read our paper here: https://arxiv.org/pdf/2312.01790.pdf . mixcmnext_mhsa contains the EarlyFusion approach, ws_cmnext_mhsa contains the Late Fusion w/ weight sharing and cmnext_mhsa is the baseline model without forensic filter fusion.

**Comment by fuqianya** [comment]
Thanks for your great help.
